### ISSUE TITLE
Option to keep ratio when resizing pictures

### ISSUE THREAD

**Issue by Fa10175** [JustCarmen/fancy_imagebar#7]
could you add an option configuration in Fancy_imagebar same that you have inside Fancy_treeview in the futur.
some on my photos are not square

**Comment by JustCarmen** [comment]
I've tried that before, but didn't succeed because the calculations to determine the amount of pictures the imagebar could hold are not easy when all pics have a different width (and you have to take into account different screen sizes too). But it is something that is still on my wish list so I'll keep this on the issue list for remembrance. It is not high on my priority list though.
